[package]
name = "neural-network-predictor"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
charming = "0.4.0"
csv = "1.3.0"
indexmap = "2.6.0"
open = "5.3.1"
rand = "0.8.5"
